[application]

name = "marie"

default_platform = "web"

out_dir = "dist"

asset_dir = "public"

[web.app]
title = "marie"

[web.watcher]
reload_html = true
watch_path = ["src", "public"]

[web.resource]
style = ["public/tailwind.css"]
script = []

[web.resource.dev]

script = []
